### ISSUE TITLE
Really great gramar

### ISSUE THREAD

**Issue by ichiriac** [camilojd/sequeljs#1]
Hi,

I would like to use your grammar file into a standalone library that just parse the SQL and returns AST, and I plan to start my work based on your grammar file.

You can take a look at the repository :
https://github.com/ichiriac/escuelle

I wanted to know if you don't mind if I release this library under the MIT license.

Thanks for sharing,
BR,
Ioan CHIRIAC

**Comment by camilojd** [comment]
Hi Ioan,

Feel free to do it! I'll add a MIT license to the repo later today.

Best,

Camilo

**Comment by ichiriac** [comment]
Hi Camilo,

Thanks for the authorization and the  MIT,

Great work, keep going,
Ioan
