### ISSUE TITLE
Online sql formatting site

### ISSUE THREAD

**Issue by trask** [camilojd/sequeljs#12]
It would be cool to host an online sql formatting site using a gh-pages branch on your repo.  I mocked up an  example at http://trask.github.io/sequeljs/, you can see the gh-pages branch serving this page at https://github.com/trask/sequeljs/tree/gh-pages.

**Comment by camilojd** [comment]
@trask I hosted it at my website some time ago (http://codespeak.cc/blog/posts/a-self-contained-sql-parser-pretty-printer.html) -- that entry now points to a dead link. Putting it directly in gh-pages seems a _much_ better idea :+1:

**Comment by camilojd** [comment]
@trask there is some cleanup needed, but I replaced the textarea for CodeMirror and is now live again at http://camilojd.github.io/sequeljs

**Comment by trask** [comment]
Nice.  Thanks.
